version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - target: 8000
        published: 8000
        mode: host

    environment:
      - NODE_ENV=production
      - BRAVE_API_KEY=${BRAVE_API_KEY}
    restart: unless-stopped 